### ISSUE TITLE
homework directory

### ISSUE THREAD

**Issue by VisheshSood** [VisheshSood/Team-NoMergeConflicts#4]
join into homework branch, and create a sub branch for each user.
cameron  - can you add the following to the homework directory:
    README.md
    index.html
    css/
        main.css
anya please add the following directories:
 js/
        app.js
    test/
        protractor-conf.js
        signup-spec.js

when you add, merge into hw so the directories are in homework branch.

**Comment by camd67** [comment]
Well, apparently we can only assign one person. Ignore those assignments....

**Comment by camd67** [comment]
Okay, got my stuff done. Anya, once you finish up you can close this issue.
