### ISSUE TITLE
Using SASS

### ISSUE THREAD

**Issue by camd67** [VisheshSood/Team-NoMergeConflicts#6]
For the CSS can I recommend using SASS? I've used it for the past assignments and in my opinion it makes the CSS way easier to read and create. ( http://sass-lang.com/guide )

I personally use Scout ( http://mhs.github.io/scout-app/ ) which basically runs in the background and recompiles the CSS whenever I make a change in the .scss file.

However, this would require we all use SASS and that we start using it now rather than later, so what does everyone think of this? If you want to see what the .scss and generated css look like you can view mine here: 
- scss: https://github.com/CamD67/challenges/blob/master/cart/css/sass/main.scss
- css: https://github.com/CamD67/challenges/blob/master/cart/css/main.css

**Comment by VisheshSood** [comment]
Sounds good to me! We should definitely use SASS because it makes everything so much cleaner and makes CSS a lot easier.
