### ISSUE TITLE
Basic HTML Layout

### ISSUE THREAD

**Issue by camd67** [VisheshSood/Team-NoMergeConflicts#8]
Fill out all the HTML for the basic page layout this should include:
- Header
- email
- First name + last name (text)
- birthday (text)
- password + confirm password (text as a password)
- reset + submit button

**NOTE:** This does not include the angular form validation, just the basic html layout. See #9  for that

**Comment by VisheshSood** [comment]
Dibs on Header and Email :)

**Comment by justmckissick** [comment]
Will be responsible for Birthday

**Comment by camd67** [comment]
Working on passwords
